### ISSUE TITLE
Test on Windows with AppVeyor and fix 32-bit

### ISSUE THREAD

**Issue by ChrisRackauckas** [ajkeller34/Unitful.jl#117]
I think there might be a problem with integer overflow with the default implementation of some units on 32-bit systems.

https://ci.appveyor.com/project/ChrisRackauckas/recursivearraytools-jl-r8tdv/build/1.0.109/job/rhcc8rvu1w3dv37u

I believe `A = zeros(5,5)*1u"kg"` is what's failing there because when it initializes the unit type there's an overflow. AppVeyor tests should be enabled for Unitful.jl so that way it can better find Windows (specifically 32-bit) errors like this.

**Comment by ajkeller34** [comment]
It is actually tested on Windows 64-bit, although I seem to have removed the badge from the README at some point. 32-bit failures have been known for [quite some time](https://github.com/JuliaLang/METADATA.jl/pull/6421) and you're the first person to mention it since then, so I imagine few people are affected. I am sorry for the inconvenience; I hope to fix this eventually but I'd welcome a PR.

**Comment by ChrisRackauckas** [comment]
It seems like it got worse though since these tests passed until recently. Could the badge be re-added to the README with 32-bit failures to indicate the problem more clearly?

**Comment by ajkeller34** [comment]
I re-added the badge.

**Comment by ChrisRackauckas** [comment]
Thanks. Where are the numbers that it's using for the conversions? I want to try placing a few `Int64` upconversions. That should be all that's required to fix it.

**Comment by ajkeller34** [comment]
Conversion factors are in pkgdefaults.jl unless I am misunderstanding what you mean.

**Comment by ajkeller34** [comment]
I fixed the "known problematic tests" on 32-bit systems although I wouldn't be surprised if there's still an overflow bug lurking around somewhere. Closing this and your PR.

**Comment by ChrisRackauckas** [comment]
Thanks!
