### ISSUE TITLE
Some details for usage in DifferentialEquations

### ISSUE THREAD

**Issue by ChrisRackauckas** [ajkeller34/Unitful.jl#12]
Hey, I was thinking of adding compatibility to this package in differential equations. I have already made the ODE parts fully compatible with SIUnits, though it seems there are limitations to that package which led me here. However, there are a few things I wanted to discuss that I couldn't find in the documentation:

1. I see that rational dimensions are accepted. This is good since Brownian motion for SDEs has a natural dimension of sqrt(dt). So for reference, does the `sqrt` function work with Unitful units?

2. How does `\` and sparse matrix multiplication do? Those would be required for the PDE solvers. SIUnits runs into problems with `\` since it calls CHOLMOD, either there needs to be a dispatch which strips the units and then puts them back on (and checks afterwards that the units work?). I'm not sure what goes wrong with SIUnits sprase matrix multiplication. I think it makes zeros that aren't unit'd and then the unit checks go wrong.

3. This package would have to get registered to be a dependency. Is that likely in the future?

4. Is there a max(x,y) for AbstractArrays of (same dimension) unit'd quantities in Unitful?

**Comment by ajkeller34** [comment]
Thanks for your interest in the package. Some responses follow:

1. Yes, `sqrt` works fine, as does raising to any other rational power. Note that `sqrt` is type-stable, but the `^` operator is not. The reason is, if you are going to encode powers of units in the type signatures of a unitful quantity, then raising that quantity to some power (a run-time value) will yield a result type that depends on that run-time value. I don't think there's a way around this unless you define some special functions like `sqrt` that are raising to a fixed power.

2. I'll have to get back to you on that, haven't checked. I guess we can define new methods for unitful quantities if needed. If you have some specific examples that you'd like to see work, I can take a look at how hard it would be to implement.

3. I plan to register this package not long after Julia 0.5 is released. I have rewritten a substantial amount of it to add functionality, and expect to finish that up soon. The `rewrite` branch of this repo contains my work in progress. It worked on 0.5-rc1 and 0.5-rc2 but some tests fail on rc3. I'm hoping this is only a temporary bug introduced into rc3 and not some breaking change. I want to finish the rewrite before registering the package since some of the types I define will change a bit.

4. It is not currently implemented but I can try to do so.

**Comment by ajkeller34** [comment]
I've implemented the `max(x,y)` and `min(x,y)` methods you requested and they will be available for use once I register the package.

**Comment by ChrisRackauckas** [comment]
Ok cool! Then I think I will be able to make everything compatible with Unitful without adding it as a dependency. That was almost the case with SIUnits (except for a few rough edges like max), and was done mostly by setting types of things like `ratetype = typeof(u/t)` (changes the dimension by time if units exists, else same type as `u`). If Unitful acts similarly with units/types (which from what I read, it does?) it should work almost out of the box.

**Comment by ajkeller34** [comment]
Apart from the `@fastmath` issue (#24), what's the current status? Should I close this issue or are there open problems you are experiencing?

**Comment by ChrisRackauckas** [comment]
This can probably close. I just tagged a new minor version, and I'll try to make sure Unitful works before the next release!

**Comment by ChrisRackauckas** [comment]
Hey, just checking back in. Unitful works great! I didn't have to require it or anything, I just got Unitful numbers and, since all of my calculations were dimensionally correct from implementing compatibility with SIUnits, it just worked. The problems that I ran into were:

- The plotting issue.
- Couldn't get master working to test `@fastmath`

Assuming `@fastmath` works once you get master able to compile, would you mind tagging a release? I'd like to add `@fastmath` and drop SIUnits. 

So good job. I am dropping support for SIUnits since it really looks like Unitful is the one true units package (haven't checked, but it probably benchmarks the same as SIUnits, right? Same method of using dispatch?)

**Comment by ajkeller34** [comment]
Happy to tag a new release. See my comment on the other issue #24, but I'll try and tag a new release today or tomorrow after you verify master works.
