### ISSUE TITLE
Getting compilation warning during precompile

### ISSUE THREAD

**Issue by djsegal** [ajkeller34/Unitful.jl#133]
I use the following line of code in one of my packages:

```julia 
const atm_conversion =
  uconvert(u"atm", 1e20u"keV/m^3") / 1u"atm"
```

However, this gives the following warnings on the initial compile:

```julia
WARNING: eval from module Unitful to FusionSystems:
Expr(:call, :^, Unitful.FreeUnits{(Unitful.Unit{:Meter, Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=1, den=1)),)}}(tens=0, power=Base.Rational{Int64}(num=1, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=1, den=1)),)}}(), 3)::Any
  ** incremental compilation may be broken for this module **

WARNING: eval from module Unitful to FusionSystems:
Expr(:call, :/, Unitful.FreeUnits{(Unitful.Unit{:eV, Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=2, den=1)), Unitful.Dimension{:Mass}(power=Base.Rational{Int64}(num=1, den=1)), Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=-2, den=1)))}}(tens=3, power=Base.Rational{Int64}(num=1, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=2, den=1)), Unitful.Dimension{:Mass}(power=Base.Rational{Int64}(num=1, den=1)), Unitful.Dimension{:Time}(power=Base.Rational{Int64}(num=-2, den=1)))}}(), Unitful.FreeUnits{(Unitful.Unit{:Meter, Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=1, den=1)),)}}(tens=0, power=Base.Rational{Int64}(num=3, den=1)),), Unitful.Dimensions{(Unitful.Dimension{:Length}(power=Base.Rational{Int64}(num=3, den=1)),)}}())::Any
  ** incremental compilation may be broken for this module **
```

How do I prevent it?

**Comment by ajkeller34** [comment]
The issue is that `@u_str` is dynamic and looks through registered modules to see what unit symbols are available at the time the macro is expanded. As a result, `@u_str` doesn't play well with precompilation. It is more explicit if slightly more annoying to write `Unitful.atm` instead of `u"atm"`, which indicates that you want Unitful's definition of `atm` even if you've registered some other modules that may define their own `atm`. I've verified that this will compile:

```
const atm_conversion =
  uconvert(Unitful.atm, 1e20*Unitful.keV/Unitful.m^3) / (Unitful.atm)

const wb_conversion =
  uconvert(Unitful.Wb, Unitful.µ0 * 1*Unitful.MA*Unitful.m) / Unitful.Wb
```

This point could use some better documentation if you're up for a PR.

**Comment by rafaqz** [comment]
I just started getting these now that 0.7 does automatic precompilation. I have some files with a few hundred unit declarations, each with 1-4 units. Adding hundreds of `Unitful.` isn't a great solution to this problem!

How about a second string macro that is Unitful specific and precompilation friendly? 

```
U"m*s^-1"
```

Otherwise my it's `using Unitful: m, s, mol, mmol, kg, g ...`

**Comment by pjabardo** [comment]
I will take a look tonight or tomorrow
