### ISSUE TITLE
Stripping units

### ISSUE THREAD

**Issue by barche** [ajkeller34/Unitful.jl#16]
Hi,

It would be useful to easily be able to strip units, e.g. for making arrays to pass to a plotting package, or for using linspace.

I know we can do `a/unit(a)`, but that's a bit verbose since it requires writing the variable name twice. Would a function like this be an acceptable addition:
```
value(a) = a.val
```

**Comment by ajkeller34** [comment]
I'm not sure how I feel about this. I had such a function in the past, but it seems like the main motivation for providing such a function is because other packages don't work perfectly with quantities yet, so ultimately it would get deprecated anyway. Perhaps you can just define such a function yourself at the start of whatever file you're working on?

**Comment by barche** [comment]
Even if a package like PyPlot supported units perfectly, it would still need to extract the unitless value at some point to pass it on to python to get a plain array of numbers. Having a function like value would simplify this, maybe we could even have one that works on arrays to do the conversion efficiently in that case?

The nice thing about having a function in the API for it is that it can be updated even if the implementation ever changes, or marked deprecated explicitly if it ever becomes unnecessary.

**Comment by ajkeller34** [comment]
I'll call it `ustrip` for unit stripping. Calling such a function `value` seems a bit ambiguous: should `value(1u"cm/m")` return `1` or `1//100`? Same goes for calling the function `unitless`, which I did previously.

As implemented now, the function has methods for`Number`s or `Array`s of them. To strip units from arrays of quantities, it just calls `reinterpret`, which will give a "unit free view" into an existing allocation of memory and should therefore be very efficient. 

Docs have been updated and tests have been added. Let me know if you need it to work for some other kind of `AbstractArray`, but I'll close this issue for now.

**Comment by barche** [comment]
OK, working perfectly, thanks!

**Comment by ajkeller34** [comment]
@barche  If you're using [Plots.jl](https://github.com/tbreloff/Plots.jl) you might try also [UnitfulPlots.jl](https://github.com/ajkeller34/UnitfulPlots.jl), which should let you plot unitful quantities without having to use `ustrip` yourself. It's a bit of a work in progress so feel free to raise an issue there if you try something that doesn't work. This uses some recent features of Plots.jl so it may not be possible to do everything perfectly yet.

**Comment by ChrisRackauckas** [comment]
I haven't gotten deep into Unitful yet, but in SIUnits you can strip units with `u/one(u)`. This is helpful because to use a function like `value` you have to import Unitful, where `u/one(u)` doesn't require Unitful to be explicit imported (can help to lower dependencies).

**Comment by ajkeller34** [comment]
`one` is by definition supposed to return the multiplicative identity. So, `one(1kg) == 1`. I just tried it in SIUnits and this is indeed the case. Dividing by that won't strip units.

It happens to work out that `(typeof(1kg))(1) == 1kg` and `(typeof(1))(1) == 1`, so you can do what you want by trying `u/(typeof(u)(1))`. This is because you are calling the constructor for the type in the case of `Quantity` or `SIQuantity`, and falling back to `convert` for "pure numeric" types like `Float64` or whatever.

One more complication: `ustrip` is advised because the above approach will change the numeric type of your quantity. Consider that `1kg/(1kg) == 1.0`, so just dividing out by 1*the unit will convert to a float. I just realized that if you need to preserve numeric types but hesitate to import things from a package, you could make things even uglier: `typeof(one(u))( u/(typeof(u)(1)) )` may work, but is quite inefficient:

```
julia> u = 1kg
1 kg 

julia> typeof(one(u))( u/(typeof(u)(1)) )
1

julia> u = 0x01kg
0x01 kg 

julia> typeof(one(u))( u/(typeof(u)(1)) )
0x01

julia> u = 0.1kg
0.1 kg 

julia> typeof(one(u))( u/(typeof(u)(1)) )
0.1
```

**Comment by ajkeller34** [comment]
Actually, I may have rushed to conclusions regarding efficiency: it takes the same amount of time as `ustrip` in some quick testing I did. So maybe doing this is the generic solution, despite ugly appearances!

**Comment by ChrisRackauckas** [comment]
Yeah, that's the version I meant: saving the type out and making a 1 of it (the way that I mentioned must've been my first try, which didn't work). It looks ugly, but works if you don't want a dependency.

**Comment by barche** [comment]
This seems a lot more verbose and obscure than having a function, IMHO (I am already a happy user of `ustrip` ;). Note that in complicated programs the variable name will be more than one letter, so having to repeat it twice or even three times gets cumbersome, even with tab completion.
