### ISSUE TITLE
ppm, ppb

### ISSUE THREAD

**Issue by cstjean** [ajkeller34/Unitful.jl#180]
Would it be reasonable to support [parts-per notation](https://en.wikipedia.org/wiki/Parts-per_notation) as dimensionless quantities: ppm, ppb, `‰`  and `%`?

**Comment by ajkeller34** [comment]
There's some of that [here](https://github.com/ajkeller34/Unitful.jl/blob/0f52452c92c5ce72bff36e40766a4603ecf17eee/src/pkgdefaults.jl#L88). I'm not sure if it was really a good idea, for all the concerns listed on the page you linked. In particular, since Unitful supports units like `mg/g` and so on, maybe using those would be less ambiguous? On the other hand, it's not really the burden of this package to police the ways people use units in practice, so I'd probably accept a PR if nobody else comments on this within a few days.

**Comment by cstjean** [comment]
On second thought, I like the policy that ambiguous units should be defined on a per-application basis. We defined `ppm` and `ppb` to be interconvertible, but not with `%`, and I would not have been comfortable "shadowing" existing units.
