### ISSUE TITLE
prefer promote(::base_unit, ::larger_unit) = base_unit 

### ISSUE THREAD

**Issue by JeffreySarnoff** [ajkeller34/Unitful.jl#3]
```julia
#  calculate one second + one hour

# converting away from a base unit
1s + 1h 
1.0002777777777778 h  # inexactness introduced

# converting into a base unit
1s + 1h                         
3601 s                # exactness preserved
```

**Comment by ajkeller34** [comment]
I agree in general that exactness should be preserved where possible. There are a few things going on here:

- The current rule (to be found in Defaults.jl) is that the resulting unit for a valid addition operation is the larger of the two units. Since `1s` < `1h`, we use `1h`. This is an arbitrary rule that introduces inexactness, as you say.

- Currently, even if we chose the smaller unit `1s`, there is a limitation in the method `basefactor(x::UnitDatum)` that will always give rise to floating-point conversion in addition operations. You can see this if you try `3600s+1h`: you will get 2.0 hours. There is no good reason for this apart from my desire to get a minimum viable package working quickly. So yes, this will hopefully change soon.

- There is really nothing special in the code about base SI units, apart from one exception. The `basefactor` methods are used to convert between units. Rather than specifying conversions between all different types of units, we just specify some numerical factor for how to represent one of a given unit in base SI units. That way we can convert between any units by going through the base SI units. This code should preserve exactness in many cases but will not preserve exactness when: a) there are exact conversions between a pair of non-SI units, but b) there are only inexact conversions between these non-SI units and the base SI units.

I hope this helps to clarify the situation.

**Comment by ajkeller34** [comment]
Default behavior is to prefer base SI units now when promotion happens. However, for those that need other behavior, this can be changed by the user in a simple way, which does not make the package dirty. In any case, imprecision should not be introduced unless the conversion between units is itself imprecise (a floating point conversion).
