### ISSUE TITLE
Defaults.jl missing from latest master issue?

### ISSUE THREAD

**Issue by goedman** [ajkeller34/Unitful.jl#36]
Hi Andrew,

Is this a problem on my side or am I updating at an unlucky moment?

In the past I had forked the Unitful.jl repository, but the last couple of weeks I just added the oil-field units I needed in my application package. Would it be'safer' for me to go back to forking Unitful.jl?

Thanks and regards,
Rob

Details:

First I got:

julia> using Unitful
INFO: Precompiling module Unitful.
ERROR: LoadError: could not open file /Users/rob/.julia/v0.5/Unitful/deps/Defaults.jl
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in defaults() at /Users/rob/.julia/v0.5/Unitful/src/User.jl:261
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/rob/.julia/v0.5/Unitful/src/Unitful.jl, in expression starting on line 878
ERROR: Failed to precompile Unitful to /Users/rob/.julia/lib/v0.5/Unitful.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?

Now I'm getting:

julia> using Unitful
INFO: Precompiling module Unitful.
ERROR: LoadError: could not open file /Users/rob/.julia/v0.5/Unitful/deps/Defaults.jl
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in defaults() at /Users/rob/.julia/v0.5/Unitful/src/User.jl:261
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/rob/.julia/v0.5/Unitful/src/Unitful.jl, in expression starting on line 878
ERROR: Failed to precompile Unitful to /Users/rob/.julia/lib/v0.5/Unitful.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?

**Comment by goedman** [comment]
Apologies, should have read to README!

**Comment by ajkeller34** [comment]
@goedman Just a heads up that the defaults system on the master branch of Unitful has been revamped. Since you seem to be using non-default units, I thought you might want to be aware of impending changes. I suggest you back up your Defaults.jl file for safe keeping, then please see the [latest documentation](https://ajkeller34.github.io/Unitful.jl/latest). If you would like to make an oil-field units package, I'm sure it would be greatly appreciated by the community (and myself, as a test to see how durable the new approach is!). Please let me know if you have questions.

**Comment by goedman** [comment]
Hi Andrew, 

Thanks for the heads up! I think I'm on the master branch (0.0.4+) and indeed recently had to drop 'oz' but otherwise my small oil field unit extensions seem to work fine. I import/create them using a small file ImportUnits.jl:

```
using Unitful

import Unitful: ft, inch, m, g, kg, °C, °, W, kW, Hz, rad, s, N, oz

#=
if !isdefined(Main, :oz)
  Unitful.@unit oz "oz" Ounce (2*2834952//(10^5))*g false
end
=#

if !isdefined(Main, :lb)
  Unitful.@unit lbf "lbf" Pound (4.45)*N true
end

if !isdefined(Main, :hp)
  Unitful.@unit hp "hp" HP (735.4990027920646)*W false
end

if !isdefined(Main, :rpm)
  Unitful.@unit rpm "rpm" RPM (1//60)*Hz false
end
```

The !isdefined() is necessary because I include ImportUnit.jl in 2 different packages, one with the finite element stuff in Fortran and another package all in Julia (the latter one will at some point be public).

I'll check the updated docs tomorrow. I know I have an outstanding, very minor, issue related in displaying DataFrames with units in the columns.

When you say 'make an oil-field units package', you mean an extension package to Unitful?

I continue to be blown away by how useful Unitful.jl is!

Regards,
Rob

**Comment by goedman** [comment]
Aaah, just saw your email on discourse. I'll try to make the oil-fields units into a package.

**Comment by ajkeller34** [comment]
Thank you for the kind words! With regards to a units package, it's as you wish—I just wanted to point out that it is possible to collect the units you've defined into a package, which others could reuse if you think it would be useful generally. If you're just defining a few units, I don't know if it would be worth your effort, but as long as it works for you, that's the most important thing of course! I must admit I am not familiar with what constitutes the full set of oil field units.

Were you to go the unit package route, either for public use or for your own private use, I'd suggest prefixing the symbols `HP`, `RPM`, etc. (third argument to the `@unit` macro) with some reasonably unique prefix to avoid collisions with other packages (`OilfieldHP`?). The reason is explained at the end of [this page](http://ajkeller34.github.io/Unitful.jl/latest/extending/). Probably I should have a mechanism to avoid this automatically... 

Best,
Andrew

**Comment by goedman** [comment]
Hi Andrew, even if for my work I only need a very small set of additional units, I see additional benefits such as getting rid of the !isdefined() clauses and, more importantly maybe, other folks can augment the package through PRs.

I don't think there is a proper definition of oil-field units, it's a mixture of US, British and SI units as far as I have seen. I'll have a stab at a UnitfulOFU package.

By the way, is there a reason the REQUIRE in UnitfulUS for Unitful is already set to 0.1.0? 

Regards,
Rob

**Comment by ajkeller34** [comment]
Ah, no reason apart from the fact that I didn’t want people to try it with Unitful 0.0.4, and that I had planned on releasing Unitful 0.1.0 in the not too distant future. Is it giving you trouble / should I set it to 0.0.4+?

Best,
Andrew

**Comment by goedman** [comment]
No, I'm ok, as long as you promise not to change UnitfulUS too often 😊
