### ISSUE TITLE
Orthogonal work at EngUnits.jl

### ISSUE THREAD

**Issue by dhoegh** [ajkeller34/Unitful.jl#5]
Good work, I have recently been working on a package called [EngUnits.jl](https://github.com/dhoegh/EngUnits.jl). The package extent SIUnits.jl to handle input and output units more gracefully. My two primary concerns when designing the package was:

- Allow units to be expressed without interfering with variable names and exporting a lot of variables.
This is handled by a string macro. So you can write: `1*u"kN/m^2" == 1000u"Pa"`. This allow for having a lot of different units without exporting them from the package and avoids cases where the unit name is overwritten.
- The other concern of the package where to get rid of the unintuitive display of `1*Newton*1*Meter`, which is displayed as `1 kg m²s⁻²`. Instead the package displays it as `J`, and the user can specify to get it displayed different by `display_unit(u"J", "N m")`. The units can also be displayed with a certain prefix as: `display_unit(u"MPa", "MPa")`. This will cause pressure to always be displayed in `MPa`. The user can change the default display values by changing a setup file created during build time of the package.

This package seem to be aiming for a versatile implementation of units. I hope some of the concerns, I have raised here can be considered, when furher improvements of this package are made. The string macro implementation, should be quite easy to port to this package. I will be happy to do it in a PR, if people find it appropriate. I do not know how easy it would be, to implement a similar output display system.

**Comment by ajkeller34** [comment]
Thank you for your interest in the package. Let me respond to both points:

### String macros
Your string macros sound like a great idea for avoiding namespace issues. I would be very happy to see a PR. To interface such a macro with Unitful.jl, my first thought would be to tweak my `uall` and `u` macros to stop exporting the variable names of units, but still make those variables within the Unitful module. Your string macro would then parse the expression you would ordinarily type if the variables were exported, but add the appropriate namespace prefix: `u"kg*m/s^2"` becomes `Unitful.kg * Unitful.m / (Unitful.s)^2` and so on. I'm sure there are other ways to do it but this seems minimally invasive. Such a user-facing change should be accompanied by updated documentation.

Whatever the ultimate solution, my preference would be to leave it up to the user if they want to use the string macro or instead do something like `using Unitful: m, kg, s`. Sometimes people including myself might want to do some quick unit manipulations starting from a clean namespace and are lazy enough to not want to type the extra few characters...

### Unit display
Right now in Unitful.jl, `N*m` and `kg*m^2/s^2` are actually different units, because `N` is implemented distinctly from `kg*m/s^2`. You can convert between equivalent units and numeric values will of course remain the same. In this way, the units are sticky: further manipulations will keep the form that you want until you convert it to something else. Comparisons still respect the units though: `1N == 1kg*m/s^2` is true. You can use `===` to see if the units are truly identical.

The display ordering of the units is a different story. If you're willing to dive into the internals of Unitful.jl a little bit you'll see that multiplying units is guaranteed to produce a uniquely ordered tuple of `UnitDatum` in the type signature of a `UnitData` object. The ordering is in part set by the `enum` around line 50 or so. This constitutes the ordering of an internal representation of a given product of units. The display ordering is the same as the ordering of the internal representation. In principle we can decouple the display order from the internal representation. This would be good to do, but in the meantime there is probably a more sensible ordering for the `enum` around line 50.

**Comment by ajkeller34** [comment]
Since the string macro has been implemented, that leaves unit display. There's another issue open for that (#18) so I'll close this issue and we can continue discussion there if desired.
