### ISSUE TITLE
`==` is not symmetric

### ISSUE THREAD

**Issue by simonbyrne** [ajkeller34/Unitful.jl#56]
```
julia> 1u"g" == 0.001u"kg"
false

julia> 0.001u"kg" == 1u"g"
true
```

Can this be handled by promotion somehow?

**Comment by ajkeller34** [comment]
Yikes, you'd think this issue would have come up by now. Good catch. I've implemented a fix on master using `promote` and added your example to the tests.

In advance of APS March Meeting (March 13-17) I'm not sure I'll have a great deal of time to test exhaustively, but do let me know if you encounter similar issues. Once CI passes I'll tag a new release anyway since this is a pretty serious error.

**Comment by simonbyrne** [comment]
Awesome, thanks!
