### ISSUE TITLE
dimension(Unitful.Length) == NoDims

### ISSUE THREAD

**Issue by mdavezac** [ajkeller34/Unitful.jl#76]
I would expect the dimension of Length?

Also:

```Julia
julia> methods(dimension, (Type{Unitful.Length},))
# 1 method for generic function "dimension":
dimension{T<:Number}(x::Type{T}) at /....../julia/v0.5/Unitful/src/Unitful.jl:242
```

Rather than `@inline dimension{T,D,U}(::Type{Quantity{T,D,U}}) = D()` on line 288

Not sure this isn't a Julia bug

**Comment by mdavezac** [comment]
I think I see what's going on. It has to do with Length being a constructor rather than a type per se.
Would it be viable to add overloads to `@derived_dimensions`

```Julia
julia> Unitful.dimension(::Type{Unitful.Length}) = Unitful.Length.body.parameters[2]();
julia> dimension(Unitful.Length)
𝐋
```

Happy to do it if you think it's the right way

**Comment by ajkeller34** [comment]
I never intended for `Length` to be used as anything other than a type alias.  The Dimensions object is `𝐋`, which can be typed (tab-completed) as \mbfL in the REPL, or in Atom, IJulia notebook, etc. This is the object that is suitable for manipulation (you can do 𝐋*𝐋 for instance). It's annoying to type, but I wanted to avoid namespace collisions given that single-letter variable names are common, and I think it's more common to manipulate units rather than dimensions directly.

I'm happy to accept a PR to clarify this in the documentation if you feel it would help. I don't think it's worth adding a method for this because I have no intention of supporting manipulation of the type aliases as if they were Dimensions objects.

**Comment by mdavezac** [comment]
Fair enough. I'm concerned that calling the function returns an incorrect result (NoDims) rather than failing though. I'll see about adding to the docs. Thanks!
