### ISSUE TITLE
Succinct display for the next log-unit

### ISSUE THREAD

**Issue by yakir12** [ajkeller34/Unitful.jl#92]
Can we have automatic formatting of units where the quantity of a unit can be expressed more sparsely with the next log-unit? So for example, `[1, 10, 1e3, 1e6]*mm` becomes `[1mm, 1cm, 1m, 1km]`. This will be super cool (and useful) if it worked for tick-labels in `Plots.jl` (and especially for axes with a log10 scale).

**Comment by ajkeller34** [comment]
Since the units are part of the type of a quantity, arrays of quantities with different units are not very efficient to work with. The current behavior of promoting (and hence getting a common unit) upon array creation is not going to change. As a sort of compromise, one might consider decoupling the display of arrays of quantities from how quantities are actually stored in an array, but that could get confusing or misleading.

Regarding Plots, that's really more of an issue for Plots.jl or UnitfulPlots.jl to handle, I think. It's probably possible but I can't say for sure.

**Comment by yakir12** [comment]
Yea, such arrays wouldn't be efficient and therefore shouldn't be widely used, nevertheless these arrays would be very useful... Such pretty printing would probably be most useful in plots, but could also be used any where text is displayed. So I'm not sure if this functionality should be in `UnitfulPlots.jl`... @ajkeller34, What do you think?

**Comment by RedPointyJackson** [comment]
Outside plot labels, what utility could this have? I found convenient that my array has the same units in all its members.

**Comment by yakir12** [comment]
I think it would only be useful for pretty printing, not much else. *Dealing* with an Array with the same units is practical, *seeing* a bunch of 1mm and 1e6mm is ugly and unintuitive..

**Comment by ajkeller34** [comment]
If you're not worried about performance, you could make an array with an abstract element type, though I wouldn't recommend this:

```
julia> Quantity[1u"mm", 1u"km"]
2-element Array{Unitful.Quantity,1}:
 1 mm
 1 km
```
